# Generated by Django 6.1.1 on 2026-09-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_remove_usuario_id_alter_usuario_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=60, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('version', models.PositiveIntegerField(default=1)),
                ('activa', models.BooleanField(db_index=True, default=False)),
                ('definicion', models.JSONField(default=dict, help_text='Schema JSON del formulario')),
                ('descripcion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de formulario',
                'verbose_name_plural': 'Plantillas de formulario',
                'db_table': 'formulario_plantilla',
                'ordering': ['-activa', '-version', 'codigo'],
            },
        ),
    ]
