# Generated by Django 6.1.1 on 2026-09-26 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_formularioplantilla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=15)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_PROGRESO', 'En Progreso'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado')], db_index=True, default='ABIERTO', max_length=20)),
                ('categoria', models.CharField(choices=[('GPS', 'GPS / Conectividad'), ('EQUIPO_EMBARCADO', 'Equipo Embarcado / Hardware'), ('APLICACION', 'Aplicación / Software'), ('PATIO', 'Patio / Operaciones'), ('OTRO', 'Otro')], default='OTRO', max_length=30)),
                ('bus_movil', models.PositiveIntegerField(blank=True, help_text='Móvil relacionado si aplica', null=True)),
                ('creado_por_codigo', models.CharField(max_length=20)),
                ('creado_por_nombre', models.CharField(max_length=120)),
                ('asignado_a_codigo', models.CharField(blank=True, max_length=20)),
                ('asignado_a_nombre', models.CharField(blank=True, max_length=120)),
                ('comentarios', models.JSONField(blank=True, default=list)),
                ('resolucion', models.TextField(blank=True, help_text='Detalle de resolución de la incidencia')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to='buses.usuario')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_creados', to='buses.usuario')),
                ('patio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='buses.patio')),
            ],
            options={
                'db_table': 'tickets',
                'ordering': ['-creado_en'],
            },
        ),
    ]
